version: '3.4'

services:
  rabbitmq:
    image: rabbitmq:3-management-alpine

  sqldata:
    image: postgres:latest
    restart: always
    ports:
      - "5432"
    volumes:
      - db_volume:/var/lib/postgresql/data
      - ./dbscripts/seed.sql :/docker-entrypoint-initdb.d/seed.sql
    environment:
      POSTGRES_USER: "dbuser"
      POSTGRES_PASSWORD: "dbpa@ssw0rd"
      POSTGRES_DB: "stecpointdb"      

  users.api:
    image: usersapi
    restart: always
    build:
      context: .
      dockerfile: ./API/Users.API/Dockerfile
    ports:
      - 5000:80
    environment:
      EVENT_BUS_HOST: "rabbitmq"
    depends_on:
      - "rabbitmq"

  organizations.api:
    image: organizationsapi
    restart: always
    build:
      context: .
      dockerfile: ./API/Organizations.API/Dockerfile
    environment:
      DB_CONNECTION_STRING: "host=sqldata;port=5432;database=stecpointdb;username=dbuser;password=dbpa@ssw0rd;"
      EVENT_BUS_HOST: "rabbitmq"
    ports:
      - 5001:80
    depends_on:
      - "sqldata"
      - "rabbitmq"
volumes: 
  db_volume:
      