version: '3.4'

services:
  rabbitmq:
    image: rabbitmq:3-management-alpine

  sqldata:
    image: mcr.microsoft.com/mssql/server:2019-latest

  users.api:
    image: usersapi
    restart: always
    build:
      context: .
      dockerfile: ./API/Users.API/Dockerfile
    ports:
      - 5000:80
    environment:
      EVENT_BUS_HOST: "rabbitmq"
    depends_on:
      - "rabbitmq"

  organizations.api:
    image: organizationsapi
    restart: always
    build:
      context: .
      dockerfile: ./API/Organizations.API/Dockerfile
    environment:
      DB_CONNECTION_STRING: Server=127.0.0.1,1433;Database=my_db;User=sa;Password=qwertY12@3;
      EVENT_BUS_HOST: "rabbitmq"
    ports:
      - 5001:80
    depends_on:
      - "sqldata"
      - "rabbitmq"